---

language: python
python: "3.7-dev"

sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible ansible-lint

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
