---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ prometheus_dir }}"
    - "{{ prometheus_rules_dir }}"

- name: Assemble config files
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: alertmanager.yml
      dest: "{{ prometheus_dir }}/alertmanager.yml"
    - src: docker-compose.yml
      dest: "{{ prometheus_dir }}/docker-compose.yml"
    - src: prometheus.yml
      dest: "{{ prometheus_dir }}/prometheus.yml"

- name: Assemble config files for Consul
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: consul.json
      dest: "{{ consul_conf_dir }}/prometheus.json"
  notify: reload consul

- name: Upload alerting rules
  copy: src=rules/{{ item }} dest={{ prometheus_rules_dir }}/{{ item }}
  with_items:
    - node.rules.yml

- name: Run service
  shell: docker-compose up -d chdir={{ prometheus_dir }}
