---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ prometheus.rules_dir }}"

- name: Assemble Prometheus and Alertmanager config
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: alertmanager.yml
      dest: "{{ prometheus.dir }}/alertmanager.yml"
    - src: prometheus.yml
      dest: "{{ prometheus.dir }}/prometheus.yml"

- name: Upload alerting rules
  copy: src=rules/{{ item }} dest={{ prometheus.rules_dir }}/{{ item }}
  with_items: "{{ prometheus.server.rules }}"
